### ISSUE TITLE
Is there any wrong with underexposed luminance component function?

### ISSUE THREAD

**Issue by Aaron9477** [GZHU-Image-Lab/CLRIQA#2]
Hi!
Thanks for your great job!
I am trying to use your method in my project. But I find out that may be there is a little wrong in the underexposed luminance component function.
![image](https://user-images.githubusercontent.com/23026333/70503712-ff296480-1b5e-11ea-89a1-8500cdaf7c34.png)
I draw a curve for the function, and the result is as follow:
![image](https://user-images.githubusercontent.com/23026333/70503802-35ff7a80-1b5f-11ea-8ce4-0dc7d6786010.png)
Look forward your reply!
Beas wishes!
Aaron

**Comment by GZHU-Image-Lab** [comment]
Dear Aaron,

Thank you for your interesting. After inspection, I haven't found anything wrong with the underexposed function so far. Your curve is correct, but maybe it is not obvious by setting the k(level) = 3 stably. In your curve, the x-axis is original value of luminance, and the y-axis is changing luminance, the range of luminance is [0, 1], so you can see that when x gets closer to 1, x is approximately equal to y, but when x gets closer to 0, the faster y goes down. Note that when luminance is low enough, it will looks like black in HVS, and if it below 0, it will be set to 0 when the map conversion back to RGB model.
 I also draw a histogram, I think it will be easy to understand, and the histogram is as follow

![image](https://user-images.githubusercontent.com/54929532/70919442-d7089c80-205b-11ea-9043-c8d1221a2c17.png)

Moreover, an illustration is shown in follow
![image](https://user-images.githubusercontent.com/54929532/70918739-8775a100-205a-11ea-8a4c-b2d436ae9c6d.png)

Yours sincerely,
Fu-Zhao Ou

**Comment by Aaron9477** [comment]
Hi, Fu-Zhao Ou!

**Comment by Aaron9477** [comment]
Hi, Fu-Zhao Ou!
Thanks for your reply!
I see. Your underexposed luminance component function focus on unbalanced dimming. The position where is darker will be more darker after the processing. Truly thanks for your explanation and your great work!
Beas wishes!
Aaron
