### ISSUE TITLE
A question about the expansion of synthetically distorted image database

### ISSUE THREAD

**Issue by badaodao** [GZHU-Image-Lab/CLRIQA#3]
Dear author:

Thanks for such a good idea! 

I have a little question for the expansion of  synthetically distorted image database. For a synthetically distorted image with a quality score, how many images are generated from it in total?  One synthetically distorted image are deformed with different types of distortion and different distortion levels, or just deformed with one distortion type which consistent with the distortion type in the original  synthetically distorted image?

looking forward to your reply. Thank you very much.

**Comment by GZHU-Image-Lab** [comment]
Hello, 

Thank you for your appreciation. In my experiment, one synthetically distorted image will be deformed with different types and levels. In other words, deform image with double synthetically distorted distortions. In fact, I also try an experiment that just deform with original distorted type. But the experience results show that the performance improvement of deforming with different types is better than deforming with one type. 

Yours sincerely,
Fu-Zhao Ou

**Comment by badaodao** [comment]
Thank you for your prompt reply, I got it clearly now.
